### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by bigzhouj** [k5h9999/keywordfilter#1]
能说下代码流程吗。现在遇到敏感词误报的情况，无法区分语义识别。

**Comment by k5h9999** [comment]
fqc.dic这个文件里面的词就是误报的，具体你可以看源码，举例：宝鸡巴士是敏感词，替换方案"宝鸡巴士@@宝鸡⊙巴士"

**Comment by k5h9999** [comment]
> 能说下代码流程吗。现在遇到敏感词误报的情况，无法区分语义识别。

fqc.dic这个文件里面的词就是误报的，具体你可以看源码，举例：宝鸡巴士是敏感词，替换方案"宝鸡巴士@@宝鸡⊙巴士"

**Comment by bigzhouj** [comment]
你好，对不在词表中的误报是否同样有用。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;k5h9999&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月21日(星期四) 晚上6:22
收件人:&nbsp;&quot;k5h9999/keywordfilter&quot;<keywordfilter@noreply.github.com&gt;;
抄送:&nbsp;&quot;bigzhouj&quot;<1005647951@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [k5h9999/keywordfilter] 你好 (#1)

**Comment by k5h9999** [comment]
> 你好，对不在词表中的误报是否同样有用。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;k5h9999&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月21日(星期四) 晚上6:22 收件人:&nbsp;&quot;k5h9999/keywordfilter&quot;<keywordfilter@noreply.github.com&gt;; 抄送:&nbsp;&quot;bigzhouj&quot;<1005647951@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [k5h9999/keywordfilter] 你好 (#1)

词你要自己收集好，wfc.dic和fqc.dic两边都要有，wfc.dic收集的是敏感词库，其中这个敏感词一定要收集在wfc.dic这个文件，fqc.dic是矫正词库，你按fqc.dic这格式就可以了，而fqc.dic这个词库的格式：宝鸡巴士@@宝鸡⊙巴士，前面是敏感词，@@后面放的是矫正词，矫正词中间要⊙此符号隔开。
